### ISSUE TITLE
The php-cs args list isn't being used

### ISSUE THREAD

**Issue by warren5236** [hootsuite/pre-commit-php#2]
I'm using the following .pre-commit-config.yaml:

    - repo: git@github.com:hootsuite/pre-commit-php.git
      sha: 1.0.0
      hooks:
      - id: php-lint
      - id: php-cs
        files: \.(php)$
        args: [--standard=PSR2 -p]

When I try to commit I get the following output:

    computer:project scottkeckwarren$ git commit -a -m "Message"
    PHP Syntax Check (Quick)......................................................................Passed
    PHP Codesniffer...............................................................................Failed
    hookid: php-cs

    \e[0;33mBegin PHP Codesniffer ...\e[0m 
    Running command vendor/bin/phpcs  src/Controller/DocumentationController.php src/Form/Documentationedit.php src/Entity/Documentation.php
    \e[1;35mErrors detected by PHP CodeSniffer ... \e[0m 

    FILE: .../src/Controller/DocumentationController.php
    --------------------------------------------------------------------------------
    FOUND 29 ERROR(S) AND 6 WARNING(S) AFFECTING 27 LINE(S)
    --------------------------------------------------------------------------------
       2 | ERROR   | Missing file doc comment
      15 | ERROR   | Missing class doc comment
      17 | ERROR   | Doc comment for "$id" missing

    ... snip ...

    /Users/scottkeckwarren/.pre-commit/repoQHfCzb/pre_commit_hooks/php-cs.sh: line 48: phpcs_args: /,: syntax error: operand expected (error token is "/,")

The files that are listed as having errors are correct in the PSR2 standard but if you run without the standard defined from the command line I get the same errors.

**Comment by vladdancer** [comment]
I've bumped into same bug.

**Comment by shihoonhootsuite** [comment]
Apologies for the late reply. This should now be resolved - let me know if there are issues.
