### ISSUE TITLE
Would you accept a PR for php-cs-fixer?

### ISSUE THREAD

**Issue by craig-davis** [hootsuite/pre-commit-php#5]
I'd like to send a PR for using [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) with this project. 

Would you be open to this?

**Comment by shihoonhootsuite** [comment]
Sure I will be open to that. I haven't used the tool myself but for the project to be a pre-commit hook for PHP projects, we should include it in.
